# Generated by Django 5.0.7 on 2025-08-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vegetable', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
