# Generated by Django 5.0.7 on 2025-08-29 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vegetable', '0004_alter_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
